// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.ColorPaletteGenerator
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("source")]
        public string Source { get; set; }

        [JsonProperty("hue")]
        public long Hue { get; set; }

        [JsonProperty("variation")]
        public string Variation { get; set; }

        [JsonProperty("colorPalette")]
        public ColorPalette[] ColorPalette { get; set; }

        [JsonProperty("colorPaletteRaw")]
        public string[] ColorPaletteRaw { get; set; }
    }

    public partial class ColorPalette
    {
        [JsonProperty("hex")]
        public string Hex { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }
    }
}
